// Small hand-copied fixture corpus (paraphrased from the site's own pages) for the search tests.
// Public-safe: no prices, amounts, client data or [confirm] markers.
export const FIXTURE_DOCS = [
  { id: 'home#e1', url: '/', title: 'Ingqiqo Executables', section: 'Meaning Coherence Assurer', type: 'page', source: 'site', tags: ['coherence', 'practice'],
    text: 'I make what an organisation knows, measures and decides mean the same thing everywhere, so its decisions can be trusted, checked and repeated.' },
  { id: 'home#e2', url: '/', title: 'The cost no one counts', section: 'Why decisions cost twice', type: 'page', source: 'site', tags: ['decision', 'cost'],
    text: 'Every organisation pays for its decisions twice: once when they are made, and again, quietly, when they are made badly, made twice, or never finished. Meaning drifts when finance, operations and the board each define a term differently.' },
  { id: 'home#e3', url: '/', title: 'Practice', section: 'One posture, five demands', type: 'page', source: 'site', tags: ['practice', 'solutionist'],
    text: 'Scientist, engineer, analyst, modeller and architect. These are not five separate roles. The Solutionist posture holds them together: one accountable practitioner who calls on each as the effort demands.' },
  { id: 'architecture#e1', url: '/architecture/', title: 'The Ingqiqo Spine', section: 'At a glance', type: 'architecture', source: 'site', tags: ['spine', 'architecture'],
    text: 'Evidence rises from the lakehouse, gains identity in master data and meaning in the semantic layer, and meets intent at judgement. Action runs on the lakebase, and its outcomes return to accountability.' },
  { id: 'architecture#e2', url: '/architecture/', title: 'The eight planes of the Spine', section: 'Planes', type: 'architecture', source: 'site', tags: ['spine', 'planes'],
    text: 'The Spine is a portable core that carries an organisation from raw evidence, through identity and meaning, to a solved and explained decision, bounded in execution and returned to strategy as correction.' },
  { id: 'architecture#e7', url: '/architecture/', title: 'Judgement', section: 'The Decision IR', type: 'architecture', source: 'site', tags: ['decision-ir', 'judgement'],
    text: 'Every decision is compiled into one typed, content-addressed program: the Decision IR. Strategy, ontology terms, mastered identities, business rules and evidence all compile into it. A solver then finds the best option inside the rules.' },
  { id: 'architecture#e10', url: '/architecture/', title: 'The Decision Warranty', section: 'Warranty', type: 'architecture', source: 'site', tags: ['warranty', 'decision'],
    text: 'The warranty promises process fidelity, not good outcomes: that a decision was made as specified, on the evidence recorded, by the authority named. It is a contractual warranty on the service, not insurance.' },
  { id: 'architecture#e12', url: '/architecture/', title: 'Quantum readiness', section: 'Post-quantum', type: 'architecture', source: 'site', tags: ['security', 'quantum'],
    text: 'Quantum computing threatens today\'s signatures, not the hash chain. The ledger keeps a seam open for quantum solvers later. The IR names its solver, so a successor can be adopted without rewriting history.' },
  { id: 'method#e3', url: '/method/', title: 'The Disciplined Decision Cycle', section: 'IDDC', type: 'method', source: 'site', tags: ['iddc', 'decision', 'method'],
    text: 'IDDC, the Ingqiqo Disciplined Decision Cycle, turns evidence and business meaning into decisions that can be checked, contested and repeated. The Moloto Doctrine frames why a decision must be finished, not merely made.' },
  { id: 'method#e5', url: '/method/', title: 'Human in the loop, by design', section: 'The person and the machine', type: 'method', source: 'site', tags: ['governance', 'method'],
    text: 'The method uses AI and automation hard, for speed and reach, and never lets them do the thinking. The cognitive work of deciding stays with people at every step. Human in the loop is a boundary, not a slogan.' },
  { id: 'method#e8', url: '/method/', title: 'A short glossary', section: 'Glossary', type: 'glossary', source: 'site', tags: ['glossary', 'coherence'],
    text: 'Pedigree: where a figure came from, and how far it can be trusted. Stakeholder view: a version of one canonical result shaped for a role. Coherence: a term meaning the same thing in every place it is used.' },
  { id: 'engage#e3', url: '/engage/', title: 'Who decides what', section: 'The human-in-the-loop boundary', type: 'page', source: 'site', tags: ['engagement', 'governance'],
    text: 'This table makes the human-in-the-loop boundary explicit. What the organisation does about a finding is decided by you. The method supplies evidence, options and a record that will stand up to scrutiny.' },
  { id: 'engage#e5', url: '/engage/', title: 'What I stand behind', section: 'Commitments', type: 'page', source: 'site', tags: ['engagement'],
    text: 'Scope and pricing are agreed in writing before work starts. The arithmetic is checked, and every figure carries its pedigree. A commitment without stated exclusions is a sales line that gets disclaimed later.' },
  { id: 'work#canvas', url: '/work/decision-canvas-dgs/', title: 'Decision Canvas', section: 'Instrument', type: 'work', source: 'site', tags: ['instrument', 'canvas', 'decision'],
    text: 'A one-page canvas that names the decision, its owner, the evidence it rests on and the rules it must respect, so that the decision can be argued with and repeated.' },
  { id: 'work#coverage', url: '/work/intrinsic-coverage-instrument/', title: 'Intrinsic Coverage Instrument', section: 'Instrument', type: 'work', source: 'site', tags: ['instrument', 'warranty'],
    text: 'Records whether a design covered what motivates the people it affects, and flags an exception when it did not. It feeds the warranty evidence.' },
  { id: 'notes#hiring', url: '/notes/', title: 'What does it really cost to say yes?', section: 'Hiring', type: 'note', source: 'site', tags: ['hiring', 'note'],
    text: 'Most offers are judged from one side. The employer asks whether the package fits the budget; almost nobody asks whether it fits the life of the person accepting it. Hire with open eyes and record why.' },
  { id: 'notes#time', url: '/notes/', title: 'The one-day-in-five problem', section: 'Time', type: 'note', source: 'site', tags: ['time', 'note'],
    text: 'Ask a team where its time goes and you will hear meetings and email. Measure it and the cause is work left unfinished upstream, definitions disputed and decisions redone.' },
];
